version: '3'

services:
  postgre:
    image: postgres:12
    container_name: postgre
    hostname: postgre
    restart: always
    environment:
    #  POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123
    #  POSTGRES_DB: mydatabase
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net1

  app:
    build: .
    image: djg:0.01
    container_name: app
    hostname: app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - net1

networks:
  net1:

volumes:
  postgres-data:
